### PR TITLE
Added location service,mapper,locationMyBatis and JsonParsor

### PR DESCRIPTION
**Pull request by Vaishnudevi86**

### CODE REVIEW

**Review by dxliang001 — COMMENTED** [review]
On your LocationMapper.xml, there is a error for the namespace, I don't see any file name ILocationRouteMapper, make sure you map all the path and try to create a file to see if Mybatis is working correctly

**Comment by dxliang001** [comment]
I don't see any error on the code, it look fine to me, but while I try to debug it, Location class was not able import it to LocationManagementMenu.java. 
I will double check with Sheetal if it's IDE problem.

**Comment by GargSheetal** [comment]
Great work on implementing the suggested changes.
1. Please add one more constructor to the model class with both the parameters(locationId, locationName) that will be useful for fetching the data from the database.
2. Remove the sqlSession.commit() statements as you are already setting autoCommit to be true in openSession(true).

Note: We will likely adjust LocationMenu class later when we will integrate our code components together.

**Review by GargSheetal — APPROVED** [review]

**Comment by GargSheetal** [comment]
[Location Model](https://trello.com/c/MvdKw2QA/12-location-model)

**Pull request merged**
