### PR TITLE
SG-Merge and clean up

### PR DESCRIPTION
**Pull request by GargSheetal**
1. Merge individual Code Components
2. Code Cleanup
3. Create a connected menu

Note : 
- Xml parsing is not working
- Didn't change LocationManagementMenu Class

### CODE REVIEW

**Comment by GargSheetal** [comment]
[Merge Individual Components and Code cleanup](https://trello.com/c/fQeJEFwY/25-merge-individual-components-and-code-cleanup)

**Comment by GargSheetal** [comment]
[Route Selection Output - XML](https://trello.com/c/hwAKyGPm/21-route-selection-output-xml)

**Comment by GargSheetal** [comment]
[Route Selection Output - Json](https://trello.com/c/CoFikUfD/20-route-selection-output-json)

**Comment by GargSheetal** [comment]
[Route Selection Output - Json](https://trello.com/c/CoFikUfD/20-route-selection-output-json)

**Review by dxliang001 — APPROVED** [review]
Small issues that if User input is out of bound it will crash

**Pull request merged**
