### PR TITLE
strategy logic

### PR DESCRIPTION
**Pull request by GargSheetal**
Created route selection strategy - shortest and cheapest
Created Route selection Menu and Helper class.

### CODE REVIEW

**Comment by GargSheetal** [comment]
[RouteSelectionStrategy- Cheapest](https://trello.com/c/fnTfpH7J/7-routeselectionstrategy-cheapest)

**Comment by GargSheetal** [comment]
[RouteSelectionStrategy- Fastest](https://trello.com/c/4SGydWDe/13-routeselectionstrategy-fastest)

**Comment by GargSheetal** [comment]
[RouteSelectionMenu](https://trello.com/c/6y4IfekF/6-routeselectionmenu)

**Comment by GargSheetal** [comment]
[RouteSelection Menu Helper](https://trello.com/c/0mYammkU/19-routeselection-menu-helper)

**Comment by GargSheetal** [comment]
Created route selection strategy - shortest and cheapest
Created Route selection Menu and Helper class.

**Review by dxliang001 — APPROVED** [review]
Good job, I don't see any issues on the strategy method, they all look good to me.

**Comment by Vaishnudevi86** [comment]
The price matrix is declared as double[][], which may lead to precision issues when comparing prices. Consider using BigDecimal for precise decimal calculations involving currency values. Otherwise the code looks good.

**Pull request merged**
