### PR TITLE
Create airlineroute and XML parser

### PR DESCRIPTION
**Pull request by dxliang001**
Create all classes for AirlineRoute:
AirlineRoute.java
AirlineRoutes.java
AirlineRouteMyBatis.java
IAirlineRouteMapper.java

Also added dml.sql for some testing data

Create class to parse output in XML format and save in resources/output folder

### CODE REVIEW

**Comment by GargSheetal** [comment]
Suggestions:

1. It will be beneficial to create a generic method to parse xml, and use that to parse both Location and AirlineRoute objects.
2. AirlineRoute model class should have Objects of the foreign key (i.e. Location originLocation and Location destinationLocation).
3. AirlineRoute model class does not have any constructors. Please create default as well as parameterized constructor.
4. During our kick-off meeting, we agreed to use XML based MyBatis implementation. Is there any specific purpose to switch to annotation-based implementation? airlineRouteMapper.xml file is empty.
5. Also, MyBatis uses Mapper interface. Is there any specific purpose for using DAO interfaces in addition to that?

**Comment by dxliang001** [comment]
Sorry for the airlineRouteMapper, I think I discard the change by accident. Had update the routemapper as it needed.
I can not do the foreign key for the location the location model to be done, will change that after the Location model.
Constructors for the ArilineRoute have been added on this commit, the Dao interfaces was added incase we may need it in the feature. 

Let me know if there is anything else that need to be change. Thanks !

**Comment by dxliang001** [comment]
> Suggestions:
> 
> 1. It will be beneficial to create a generic method to parse xml, and use that to parse both Location and AirlineRoute objects.
> 2. AirlineRoute model class should have Objects of the foreign key (i.e. Location originLocation and Location destinationLocation).
> 3. AirlineRoute model class does not have any constructors. Please create default as well as parameterized constructor.
> 4. During our kick-off meeting, we agreed to use XML based MyBatis implementation. Is there any specific purpose to switch to annotation-based implementation? airlineRouteMapper.xml file is empty.
> 5. Also, MyBatis uses Mapper interface. Is there any specific purpose for using DAO interfaces in addition to that?

Thanks for the review, Sorry that I miss the airlineRouteMapper.xml, I think I discard the change by accident, now it has been added. I also create the a generic method to parse xml and you mentioned feel free to have a look. 
I also added the foreign key for Location originLocation and Location destinationLocation
The dao interfaces was added incase we may need it, it wasn't use right now, I can delete it if we have to.

Let me know if there's any change that I have to make, I will work on it ASAP.

**Comment by GargSheetal** [comment]
[AirlineRoute Model](https://trello.com/c/zzkjhuQr/4-airlineroute-model)

**Comment by GargSheetal** [comment]
Great work on implementing the suggested changes.

Here are some of the suggestions to incorporate:
1. Please add one more constructor to the model class with all the parameters (including int routeId) that will be useful for fetching the data from the database.
2. Add the getter function in AirlineRoutes class.
3. airlineRouteMapper.xml file -  In the resultMap's <association> tag, please add javatype attribute and change the resultMap.
    -  javaType - indicates the class that represents the associated object. It should be the packageName.className of the 
       associated object i.e. solvd.airline.dataaccess.model.Location.Location
    - resultMap -  add the resultMap of the associated object i.e. 
      solvd.airline.dataaccess.model.Location.LocationMapper.locationResultMap
    -  This will make the association simpler.
  
4. You can keep your association if your code is working. Point 3 is just a suggestion to make the association look simpler.
5. Use camelCasing for resultMap id. AirLineRouteResult -> airLineRouteResult
6. Remove ``/'' from the database queries. You can refer to VaishnuDevi's mapper.xml file. Also create a get/Select query without joins.

**Review by GargSheetal — APPROVED** [review]

**Pull request merged**
